# Generated by Django 4.0.1 on 2024-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(blank=True, default='0', max_length=13, null=True),
        ),
    ]
