# Generated by Django 4.0.1 on 2024-04-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='customer',
            new_name='cust',
        ),
    ]
