# Generated by Django 4.0.1 on 2024-04-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='invetsed',
            new_name='invested',
        ),
    ]
