# Generated by Django 4.0.1 on 2024-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_amount_alter_order_buy_and_more'),
        ('relationship', '0002_rename_invetsed_relationship_invested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='orders',
        ),
        migrations.AddField(
            model_name='relationship',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='order.Order'),
        ),
    ]
