# Generated by Django 4.0.1 on 2024-04-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_user_order_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
