# Generated by Django 4.0.1 on 2024-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
